"""
PPT Generator Module
Generates PowerPoint presentations based on AI analysis results
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
import os
from datetime import datetime
import uuid

class PPTGenerator:
    def __init__(self):
        self.exports_dir = "exports"
        if not os.path.exists(self.exports_dir):
            os.makedirs(self.exports_dir)
    
    def create_base_presentation(self, title="AI Analysis Report"):
        """Create a base presentation with company branding"""
        prs = Presentation()
        
        # Set slide size to 16:9
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)
        
        return prs
    
    def add_title_slide(self, prs, title, subtitle="Generated by Craveva AI"):
        """Add a title slide to the presentation"""
        title_slide_layout = prs.slide_layouts[0]  # Title slide layout
        slide = prs.slides.add_slide(title_slide_layout)
        
        # Set title
        title_shape = slide.shapes.title
        title_shape.text = title
        title_shape.text_frame.paragraphs[0].font.size = Pt(44)
        title_shape.text_frame.paragraphs[0].font.bold = True
        title_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(139, 90, 60)  # Brand color
        
        # Set subtitle
        subtitle_shape = slide.placeholders[1]
        subtitle_shape.text = subtitle
        subtitle_shape.text_frame.paragraphs[0].font.size = Pt(24)
        subtitle_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(100, 100, 100)
        
        return slide
    
    def add_content_slide(self, prs, title, content_points):
        """Add a content slide with bullet points"""
        bullet_slide_layout = prs.slide_layouts[1]  # Title and Content layout
        slide = prs.slides.add_slide(bullet_slide_layout)
        
        # Set title
        title_shape = slide.shapes.title
        title_shape.text = title
        title_shape.text_frame.paragraphs[0].font.size = Pt(32)
        title_shape.text_frame.paragraphs[0].font.bold = True
        title_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(139, 90, 60)
        
        # Add content
        content_shape = slide.placeholders[1]
        text_frame = content_shape.text_frame
        text_frame.clear()
        
        for i, point in enumerate(content_points):
            if i == 0:
                p = text_frame.paragraphs[0]
            else:
                p = text_frame.add_paragraph()
            
            p.text = point
            p.level = 0
            p.font.size = Pt(18)
            p.font.color.rgb = RGBColor(50, 50, 50)
        
        return slide
    
    def add_two_column_slide(self, prs, title, left_content, right_content):
        """Add a two-column content slide"""
        two_content_layout = prs.slide_layouts[3]  # Two Content layout
        slide = prs.slides.add_slide(two_content_layout)
        
        # Set title
        title_shape = slide.shapes.title
        title_shape.text = title
        title_shape.text_frame.paragraphs[0].font.size = Pt(32)
        title_shape.text_frame.paragraphs[0].font.bold = True
        title_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(139, 90, 60)
        
        # Left column
        left_shape = slide.placeholders[1]
        left_text_frame = left_shape.text_frame
        left_text_frame.clear()
        
        for i, point in enumerate(left_content):
            if i == 0:
                p = left_text_frame.paragraphs[0]
            else:
                p = left_text_frame.add_paragraph()
            p.text = point
            p.font.size = Pt(16)
            p.font.color.rgb = RGBColor(50, 50, 50)
        
        # Right column
        right_shape = slide.placeholders[2]
        right_text_frame = right_shape.text_frame
        right_text_frame.clear()
        
        for i, point in enumerate(right_content):
            if i == 0:
                p = right_text_frame.paragraphs[0]
            else:
                p = right_text_frame.add_paragraph()
            p.text = point
            p.font.size = Pt(16)
            p.font.color.rgb = RGBColor(50, 50, 50)
        
        return slide
    
    def generate_products_services_ppt(self, analysis_data, conversation_id):
        """Generate PPT for Products & Services analysis"""
        prs = self.create_base_presentation()
        
        # Title slide
        self.add_title_slide(prs, "Products & Services Analysis", "Comprehensive Product Portfolio Review")
        
        # Overview slide
        overview_points = [
            "Product portfolio performance analysis",
            "Service delivery metrics and quality assessment",
            "Market positioning and competitive advantages",
            "Customer satisfaction and feedback analysis",
            "Revenue contribution by product/service category"
        ]
        self.add_content_slide(prs, "Analysis Overview", overview_points)
        
        # Key findings slide
        if isinstance(analysis_data, str):
            # Parse the analysis data into key points
            key_points = self._extract_key_points(analysis_data, "products and services")
        else:
            key_points = [
                "Top performing products identified",
                "Service quality improvements recommended",
                "Market expansion opportunities discovered",
                "Customer retention strategies proposed"
            ]
        
        self.add_content_slide(prs, "Key Findings", key_points)
        
        # Recommendations slide
        recommendations = [
            "Optimize high-performing product lines",
            "Enhance service delivery processes",
            "Develop new market entry strategies",
            "Implement customer feedback systems",
            "Focus on profitable service categories"
        ]
        self.add_content_slide(prs, "Strategic Recommendations", recommendations)
        
        # Save the presentation
        filename = f"ppt_ProductsServices_{conversation_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        filepath = os.path.join(self.exports_dir, filename)
        prs.save(filepath)
        
        return filepath
    
    def generate_market_clients_ppt(self, analysis_data, conversation_id):
        """Generate PPT for Market & Clients analysis"""
        prs = self.create_base_presentation()
        
        # Title slide
        self.add_title_slide(prs, "Market & Clients Analysis", "Market Insights and Customer Intelligence")
        
        # Market overview
        market_points = [
            "Market size and growth trends",
            "Competitive landscape analysis",
            "Customer segmentation insights",
            "Market share and positioning",
            "Emerging opportunities and threats"
        ]
        self.add_content_slide(prs, "Market Overview", market_points)
        
        # Client analysis
        client_points = [
            "Customer demographics and behavior",
            "Client acquisition and retention rates",
            "Customer lifetime value analysis",
            "Satisfaction scores and feedback",
            "Churn analysis and prevention strategies"
        ]
        self.add_content_slide(prs, "Client Analysis", client_points)
        
        # Two-column insights
        market_insights = [
            "Market growth rate: Positive trend",
            "Competition: Moderate intensity",
            "Opportunities: Digital transformation"
        ]
        client_insights = [
            "Customer satisfaction: 85% positive",
            "Retention rate: Above industry average",
            "Growth potential: High-value segments"
        ]
        self.add_two_column_slide(prs, "Market vs Client Insights", market_insights, client_insights)
        
        # Save the presentation
        filename = f"ppt_MarketClients_{conversation_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        filepath = os.path.join(self.exports_dir, filename)
        prs.save(filepath)
        
        return filepath
    
    def generate_performance_growth_ppt(self, analysis_data, conversation_id):
        """Generate PPT for Performance & Growth analysis"""
        prs = self.create_base_presentation()
        
        # Title slide
        self.add_title_slide(prs, "Performance & Growth Analysis", "Business Performance and Growth Strategy")
        
        # Performance metrics
        performance_points = [
            "Revenue growth and profitability trends",
            "Operational efficiency indicators",
            "Key performance metrics analysis",
            "Productivity and resource utilization",
            "Financial health assessment"
        ]
        self.add_content_slide(prs, "Performance Metrics", performance_points)
        
        # Growth opportunities
        growth_points = [
            "Market expansion possibilities",
            "Product development opportunities",
            "Strategic partnerships potential",
            "Technology adoption benefits",
            "Scalability and capacity planning"
        ]
        self.add_content_slide(prs, "Growth Opportunities", growth_points)
        
        # Action plan
        action_points = [
            "Short-term performance improvements",
            "Medium-term growth initiatives",
            "Long-term strategic objectives",
            "Resource allocation priorities",
            "Success metrics and KPIs"
        ]
        self.add_content_slide(prs, "Action Plan", action_points)
        
        # Save the presentation
        filename = f"ppt_PerformanceGrowth_{conversation_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        filepath = os.path.join(self.exports_dir, filename)
        prs.save(filepath)
        
        return filepath
    
    def generate_strategy_vision_ppt(self, analysis_data, conversation_id):
        """Generate PPT for Strategy & Vision analysis"""
        prs = self.create_base_presentation()
        
        # Title slide
        self.add_title_slide(prs, "Strategy & Vision Analysis", "Strategic Planning and Future Vision")
        
        # Current strategy assessment
        strategy_points = [
            "Current strategic position analysis",
            "Competitive advantages and differentiators",
            "Strategic goals alignment assessment",
            "Resource allocation effectiveness",
            "Strategic risk evaluation"
        ]
        self.add_content_slide(prs, "Current Strategy Assessment", strategy_points)
        
        # Vision and future direction
        vision_points = [
            "Long-term vision and mission alignment",
            "Future market positioning strategy",
            "Innovation and transformation roadmap",
            "Sustainability and growth objectives",
            "Stakeholder value creation plan"
        ]
        self.add_content_slide(prs, "Vision & Future Direction", vision_points)
        
        # Strategic recommendations
        strategic_recs = [
            "Strategic focus areas prioritization",
            "Competitive positioning enhancement",
            "Innovation investment recommendations"
        ]
        implementation_recs = [
            "Implementation timeline and milestones",
            "Resource requirements and allocation",
            "Success measurement framework"
        ]
        self.add_two_column_slide(prs, "Strategic Recommendations", strategic_recs, implementation_recs)
        
        # Save the presentation
        filename = f"ppt_StrategyVision_{conversation_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        filepath = os.path.join(self.exports_dir, filename)
        prs.save(filepath)
        
        return filepath
    
    def generate_proposal_ppt(self, analysis_data, conversation_id):
        """Generate PPT for Proposal presentation"""
        prs = self.create_base_presentation()
        
        # Title slide
        self.add_title_slide(prs, "Business Proposal", "Strategic Recommendations and Implementation Plan")
        
        # Executive summary
        summary_points = [
            "Situation analysis and key findings",
            "Proposed solution overview",
            "Expected benefits and outcomes",
            "Investment requirements",
            "Implementation timeline"
        ]
        self.add_content_slide(prs, "Executive Summary", summary_points)
        
        # Problem and opportunity
        problem_points = [
            "Current challenges identified",
            "Market opportunities available",
            "Competitive threats to address",
            "Operational gaps to fill"
        ]
        self.add_content_slide(prs, "Problem & Opportunity", problem_points)
        
        # Proposed solution
        solution_points = [
            "Comprehensive solution framework",
            "Key components and features",
            "Implementation methodology",
            "Success factors and enablers",
            "Risk mitigation strategies"
        ]
        self.add_content_slide(prs, "Proposed Solution", solution_points)
        
        # Investment and returns
        investment_details = [
            "Initial investment requirements",
            "Operational cost considerations",
            "Resource allocation needs"
        ]
        return_details = [
            "Expected ROI and payback period",
            "Quantifiable benefits",
            "Long-term value creation"
        ]
        self.add_two_column_slide(prs, "Investment & Returns", investment_details, return_details)
        
        # Next steps
        next_steps = [
            "Immediate action items",
            "Decision timeline",
            "Stakeholder engagement plan",
            "Project kickoff requirements",
            "Success measurement criteria"
        ]
        self.add_content_slide(prs, "Next Steps", next_steps)
        
        # Save the presentation
        filename = f"ppt_Proposal_{conversation_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        filepath = os.path.join(self.exports_dir, filename)
        prs.save(filepath)
        
        return filepath
    
    def _extract_key_points(self, analysis_text, category):
        """Extract key points from analysis text"""
        # Simple extraction logic - can be enhanced with NLP
        sentences = analysis_text.split('.')
        key_points = []
        
        for sentence in sentences[:5]:  # Take first 5 sentences
            sentence = sentence.strip()
            if len(sentence) > 20:  # Filter out very short sentences
                key_points.append(sentence)
        
        if not key_points:
            key_points = [
                f"Comprehensive {category} analysis completed",
                "Key insights and trends identified",
                "Strategic recommendations developed",
                "Implementation roadmap created"
            ]
        
        return key_points
    
    def generate_ppt_by_type(self, ppt_type, analysis_data, conversation_id):
        """Generate PPT based on the specified type"""
        type_mapping = {
            'ProductsServices': self.generate_products_services_ppt,
            'MarketClients': self.generate_market_clients_ppt,
            'PerformanceGrowth': self.generate_performance_growth_ppt,
            'StrategyVision': self.generate_strategy_vision_ppt,
            'Proposal': self.generate_proposal_ppt
        }
        
        if ppt_type in type_mapping:
            return type_mapping[ppt_type](analysis_data, conversation_id)
        else:
            raise ValueError(f"Unknown PPT type: {ppt_type}")