runtime: php81
env: standard
beta_settings:
  cloud_sql_instances: craveva-org-55934-project:asia-southeast1:craveva-sql-db
runtime_config:
  document_root: public
handlers:
- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots.txt
- url: /storage
  static_dir: public/storage
- url: /assets
  static_dir: public/assets
- url: /.*
  script: auto
env_variables:
  APP_ENV: production
  APP_DEBUG: false
  APP_URL: https://hub.craveva.com
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: hub.craveva.com
  DB_USERNAME: hubcraveva
  DB_PASSWORD: '986L$o_}?tg-yeH|'
  DB_SOCKET: /cloudsql/craveva-org-55934-project:asia-southeast1:craveva-sql-db
  QUEUE_CONNECTION: sync
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  TELESCOPE_ENABLED: false
