name: deploy-whatsapp-production
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: echo target
        run: echo "Deploy to GCP project craveva-whatsapp"
