name: deploy-craveva-hub-server
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: echo target
        run: echo "Deploy naming based on VM craveva-hub-server"
